//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbaProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int doctor_id { get; set; }
        public string doctor_name { get; set; }
        public string doctor_surname { get; set; }
        public Nullable<System.DateTime> doctor_dateofbirh { get; set; }
        public string doctor_city { get; set; }
        public string doctor_speciality { get; set; }
        public Nullable<decimal> doctor_phonenumber { get; set; }
    }
}
