//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbaProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int patient_id { get; set; }
        public string patient_name { get; set; }
        public string patient_surname { get; set; }
        public Nullable<System.DateTime> patient_dateofbirth { get; set; }
        public string patient_address { get; set; }
        public string patient_phonenumber { get; set; }
        public string patient_city { get; set; }
    }
}
