//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbaProjekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int reminder_id { get; set; }
        public Nullable<System.DateTime> date_of_previous_checkup { get; set; }
        public Nullable<System.DateTime> date_of_next_checkup { get; set; }
        public string patient_name { get; set; }
        public string type { get; set; }
        public string doctor_name { get; set; }
    }
}
